services:
  intent_catcher:
    build:
      context: services/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=chatsky.ipavlov.mipt.ru:8001
      - PORT=8000
    networks:
      - assistant-network

  llm_llama3:
    build:
      context: services/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=chatsky.ipavlov.mipt.ru:8004
      - PORT=8000
    networks:
      - assistant-network

  machine_translation:
    build:
      context: services/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=chatsky.ipavlov.mipt.ru:8005
      - PORT=8000
    networks:
      - assistant-network

  gigachat:
    build:
      context: services/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=chatsky.ipavlov.mipt.ru:8006
      - PORT=8000
    networks:
      - assistant-network

networks:
  assistant-network:
    driver: bridge
